name: 'Typesafe.js Compile'
description: 'Compiles JavaScript'
inputs:
  lerna: 
    description: 'Whether lerna is enabled'
    required: true
    default: true
  node-version:  # id of input
    descriotion: 'Version of node to use'
    required: true
    default: 16
  npm-client:
    description: 'The npm client to use'
    required: true
    default: 'yarn'
runs:
  runs:
  using: 'node16'
  main: './packages/action/lib/compile.js'