name: test

on:
  push:
    branches:
      - '**'
    paths:
      - '**.js'
      - '**.yml'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: test
      uses: ./action/compile